---
name: manifests

on:
  push:
    branches:
      - 'manifests-jdks'
  pull_request:
    paths:
      - 'manifests/**/*.yml'
      - '!manifests/templates/**/'

jobs:
  list-changed-manifests:
    runs-on: ubuntu-latest
    outputs:
      matrix_1x: ${{ steps.set-matrix-1x.outputs.matrix_1x }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get changed manifest files in 1x
        uses: tj-actions/changed-files@v39
        id: list-changed-manifests-1x
        with:
          files: |
            manifests/**/opensearch-1*.yml
            manifests/**/opensearch-dashboards-1*.yml
          json: true
          quotepath: false
          dir_names: false

      - name: Set unique changed manifests as matrix 1x
        id: set-matrix-1x
        run: |
          if ${{ steps.list-changed-manifests-1x.outputs.any_changed }}; then
            echo "matrix_1x={\"manifest\":${{ steps.list-changed-manifests-1x.outputs.all_changed_files }}, \"jdk\": \"[11]\"}" >> "$GITHUB_OUTPUT"
          else
            echo "No 1x changes"
          fi

  test:
    needs: [list-changed-manifests]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ fromJson(needs.list-changed-manifests.outputs.matrix_1x) }}

  manifest-checks-1x:
    needs: [list-changed-manifests]
    if: ${{ needs.list-changed-manifests.outputs.matrix_1x }}
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.9
    strategy:
      matrix: ${{ fromJson(needs.list-changed-manifests.outputs.matrix_1x) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install Pipenv and Dependencies
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: OpenSearch Manifests
        run: |-
          ./ci.sh ${{ matrix.manifest }} --snapshot

#  manifest-checks-jdk17:
#    needs: [list-changed-manifests]
#    if: contains(matrix.manifest, 'opensearch-2') || contains(matrix.manifest, 'opensearch-dashboards-2')
#    runs-on: ubuntu-latest
#    env:
#      PYTHON_VERSION: 3.9
#      JDK_VERSION: 17
#    strategy:
#      matrix: ${{ fromJson(needs.list-changed-manifests.outputs.matrix) }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set Up JDK ${{ env.JDK_VERSION }}
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ env.JDK_VERSION }}
#      - name: Set up Python ${{ env.PYTHON_VERSION }}
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ env.PYTHON_VERSION }}
#      - name: Install Pipenv and Dependencies
#        run: |
#          python -m pip install --upgrade pipenv wheel
#      - name: OpenSearch Manifests
#        run: |-
#          ./ci.sh ${{ matrix.manifest }} --snapshot

#  manifest-checks-jdk21:
#    needs: [list-changed-manifests]
#    if: ${{ contains(env.matrix.manifest, 'opensearch-3') }}
#    runs-on: ubuntu-latest
#    env:
#      PYTHON_VERSION: 3.9
#      JDK_VERSION: 21
#    strategy:
#      matrix: ${{ fromJson(needs.list-changed-manifests.outputs.matrix) }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set Up JDK ${{ env.JDK_VERSION }}
#        uses: actions/setup-java@v1
#        with:
#          java-version: ${{ env.JDK_VERSION }}
#      - name: Set up Python ${{ env.PYTHON_VERSION }}
#        uses: actions/setup-python@v3
#        with:
#          python-version: ${{ env.PYTHON_VERSION }}
#      - name: Install Pipenv and Dependencies
#        run: |
#          python -m pip install --upgrade pipenv wheel
#      - name: OpenSearch Manifests
#        run: |-
#          ./ci.sh ${{ matrix.manifest }} --snapshot
